### ISSUE TITLE
Bug - PnmlReader failed to sort places index

### ISSUE THREAD

**Issue by juanjoarce7456** [airabinovich/java_petri_engine#1]
MonitorManager creation failed because of PnmlReader being unable to sort places index correctly.
PNML files and error stacktrace attached

[errorStacktrace.txt](https://github.com/airabinovich/java_petri_engine/files/468789/errorStacktrace.txt)

[pnmls.zip](https://github.com/airabinovich/java_petri_engine/files/468792/pnmls.zip)

**Comment by airabinovich** [comment]
This issue is caused because the parser supposes places and transition have their standard names where the index is embedded into (e.g p5).
This allows to maintain the user-specified order for places in matrix rows and transition in matrix columns.

We agreed it's better to allow the user to use any name for places and transitions, store that custom name and assign an index for each place or transition as it is parsed

**Comment by airabinovich** [comment]
Ready to verify @juanjoarce7456
